export const pageDesignMap = [
    { id: 1, name: '意见反馈', route: '/business/pages/business_pages/feedback', file: 'business/pages/business_pages/feedback.vue', type: 'scene' },
    { id: 2, name: '消息通知-详情', route: '/bundle_misc/pages/notice_detail/notice_detail?title=%E7%B3%BB%E7%BB%9F%E9%80%9A%E7%9F%A5&time=2026-05-10%2010%3A00%3A00&content=%E8%BF%99%E6%98%AF%E7%B3%BB%E7%BB%9F%E9%80%9A%E7%9F%A5%E8%AF%A6%E6%83%85%E7%A4%BA%E4%BE%8B', file: 'bundle_misc/pages/notice_detail/notice_detail.vue', type: 'business' },
    { id: 3, name: '店铺详情', route: '/business/pages/business_pages/store_detail', file: 'business/pages/business_pages/store_detail.vue', type: 'scene' },
    { id: 4, name: '首页', route: '/pages/index/index', file: 'pages/index/index.vue', type: 'business', openType: 'switchTab' },
    { id: 5, name: '商街', route: '/pages/street/street', file: 'pages/street/street.vue', type: 'scene', openType: 'switchTab'  },
    { id: 6, name: '待付款', route: '/business/pages/business_pages/pending_payment', file: 'business/pages/business_pages/pending_payment.vue', type: 'scene' },
    { id: 7, name: '店铺详情-二维码', route: '/business/pages/business_pages/store_qr', file: 'business/pages/business_pages/store_qr.vue', type: 'scene' },
    { id: 8, name: '店铺详情-商品二维码', route: '/business/pages/business_pages/goods_qr', file: 'business/pages/business_pages/goods_qr.vue', type: 'scene' },
    { id: 9, name: '法币余额', route: '/bundle_finance/pages/user_wallet/user_wallet', file: 'bundle_finance/pages/user_wallet/user_wallet.vue', type: 'business' },
    { id: 10, name: '分类', route: '/pages/sort/sort', file: 'pages/sort/sort.vue', type: 'business', openType: 'switchTab' },
    { id: 11, name: '付款记录', route: '/business/pages/business_pages/payment_record', file: 'business/pages/business_pages/payment_record.vue', type: 'scene' },
    { id: 12, name: '购物车', route: '/pages/shop_cart/shop_cart', file: 'pages/shop_cart/shop_cart.vue', type: 'business', openType: 'switchTab' },
    { id: 13, name: '关于我们', route: '/business/pages/business_pages/about_us', file: 'business/pages/business_pages/about_us.vue', type: 'scene' },
    { id: 14, name: '活动中心', route: '/business/pages/business_pages/activity_center', file: 'business/pages/business_pages/activity_center.vue', type: 'scene' },
    { id: 15, name: '介绍名片', route: '/business/pages/business_pages/intro_card', file: 'business/pages/business_pages/intro_card.vue', type: 'scene' },
    { id: 16, name: '面对面付款', route: '/business/pages/business_pages/face_pay', file: 'business/pages/business_pages/face_pay.vue', type: 'scene' },
    { id: 17, name: '最近访问', route: '/business/pages/business_pages/recent_visits', file: 'business/pages/business_pages/recent_visits.vue', type: 'scene' },
    { id: 18, name: '商家资质', route: '/bundle_user/pages/license/license', file: 'bundle_user/pages/license/license.vue', type: 'business' },
    { id: 19, name: '商街-商品', route: '/business/pages/business_pages/street_goods', file: 'business/pages/business_pages/street_goods.vue', type: 'scene' },
    { id: 20, name: '商品详情', route: '/bundle/pages/goods_details/goods_details?id=1', file: 'bundle/pages/goods_details/goods_details.vue', type: 'business', needsData: true },
    { id: 21, name: '生态应用', route: '/business/pages/business_pages/eco_app', file: 'business/pages/business_pages/eco_app.vue', type: 'scene' },
    { id: 23, name: '搜索列表', route: '/bundle/pages/goods_search/goods_search', file: 'bundle/pages/goods_search/goods_search.vue', type: 'business' },
    { id: 24, name: '收货地址', route: '/bundle/pages/user_address/user_address', file: 'bundle/pages/user_address/user_address.vue', type: 'business' },
    { id: 25, name: '编辑地址', route: '/bundle/pages/address_edit/address_edit', file: 'bundle/pages/address_edit/address_edit.vue', type: 'business' },
    { id: 26, name: '我的', route: '/pages/user/user', file: 'pages/user/user.vue', type: 'business', openType: 'switchTab' },
    { id: 27, name: '我的订单', route: '/bundle_order/pages/user_order/user_order', file: 'bundle_order/pages/user_order/user_order.vue', type: 'business' },
    { id: 28, name: '消息通知', route: '/bundle_misc/pages/notice/notice', file: 'bundle_misc/pages/notice/notice.vue', type: 'business' },
    { id: 29, name: '用户KYC', route: '/business/pages/business_pages/user_kyc', file: 'business/pages/business_pages/user_kyc.vue', type: 'scene' },
    { id: 30, name: '积分签到', route: '/bundle_misc/pages/user_sign/user_sign', file: 'bundle_misc/pages/user_sign/user_sign.vue', type: 'business' },
    { id: 31, name: '积分明细', route: '/bundle_misc/pages/sign_detail/sign_detail', file: 'bundle_misc/pages/sign_detail/sign_detail.vue', type: 'business' },
    { id: 32, name: '我的优惠券', route: '/bundle_user/pages/user_coupon/user_coupon', file: 'bundle_user/pages/user_coupon/user_coupon.vue', type: 'business' },
    { id: 33, name: '商品评价列表', route: '/bundle_order/pages/goods_comment_list/goods_comment_list', file: 'bundle_order/pages/goods_comment_list/goods_comment_list.vue', type: 'business' },
    { id: 34, name: '退款/售后', route: '/bundle_order/pages/post_sale/post_sale', file: 'bundle_order/pages/post_sale/post_sale.vue', type: 'business' },
    { id: 35, name: '自动领取积分设置', route: '/business/pages/business_pages/auto_points', file: 'business/pages/business_pages/auto_points.vue', type: 'business' },
]
