export const pageDesignMap = [
    { id: 1, name: '介绍名片', route: '/business/pages/business_pages/intro_card?preview=1', file: 'business/pages/business_pages/intro_card.vue', type: 'scene' },
    { id: 2, name: '优惠券', route: '/bundle_user/pages/user_coupon/user_coupon', file: 'bundle_user/pages/user_coupon/user_coupon.vue', type: 'business' },
    { id: 3, name: '关于我们', route: '/business/pages/business_pages/about_us', file: 'business/pages/business_pages/about_us.vue', type: 'scene' },
    { id: 4, name: '商品详情', route: '/bundle/pages/goods_details/goods_details', file: 'bundle/pages/goods_details/goods_details.vue', type: 'business', needsData: true },
    { id: 5, name: '商城', route: '/pages/street/street', file: 'pages/street/street.vue', type: 'business', openType: 'switchTab' },
    { id: 6, name: '店铺详情', route: '/business/pages/business_pages/store_detail?preview=1', file: 'business/pages/business_pages/store_detail.vue', type: 'scene' },
    { id: 7, name: '店铺详情--团购', route: '/business/pages/business_pages/store_group?preview=1', file: 'business/pages/business_pages/store_group.vue', type: 'scene' },
    { id: 8, name: '店铺详情--相册', route: '/business/pages/business_pages/store_album?preview=1', file: 'business/pages/business_pages/store_album.vue', type: 'scene' },
    { id: 9, name: '店铺详情--视频', route: '/business/pages/business_pages/store_detail?preview=1&tab=video', file: 'business/pages/business_pages/store_detail.vue', type: 'scene' },
    { id: 10, name: '店铺详情--评价', route: '/business/pages/business_pages/store_detail?preview=1&tab=comment', file: 'business/pages/business_pages/store_detail.vue', type: 'scene' },
    { id: 11, name: '待付款', route: '/business/pages/business_pages/pending_payment', file: 'business/pages/business_pages/pending_payment.vue', type: 'scene' },
    { id: 12, name: '暂未开放', route: '/business/pages/business_pages/developing', file: 'business/pages/business_pages/developing.vue', type: 'business' },
    { id: 13, name: '意见反馈', route: '/business/pages/business_pages/feedback', file: 'business/pages/business_pages/feedback.vue', type: 'scene' },
    { id: 14, name: '我的', route: '/pages/user/user', file: 'pages/user/user.vue', type: 'business', openType: 'switchTab' },
    { id: 15, name: '我的订单', route: '/bundle_order/pages/user_order/user_order', file: 'bundle_order/pages/user_order/user_order.vue', type: 'business' },
    { id: 16, name: '搜索列表', route: '/bundle/pages/goods_search/goods_search', file: 'bundle/pages/goods_search/goods_search.vue', type: 'business' },
    { id: 17, name: '消息通知', route: '/bundle_misc/pages/notice/notice', file: 'bundle_misc/pages/notice/notice.vue', type: 'business' },
    { id: 18, name: '消息通知--详情', route: '/bundle_misc/pages/notice_detail/notice_detail', file: 'bundle_misc/pages/notice_detail/notice_detail.vue', type: 'business', needsData: true },
    { id: 19, name: '添加地址', route: '/bundle/pages/address_edit/address_edit', file: 'bundle/pages/address_edit/address_edit.vue', type: 'business' },
    { id: 20, name: '添加地址--空', route: '/bundle/pages/user_address/user_address', file: 'bundle/pages/user_address/user_address.vue', type: 'business' },
    { id: 21, name: '渠道服务商', route: '/business/pages/business_pages/promoter_apply', file: 'business/pages/business_pages/promoter_apply.vue', type: 'business' },
    { id: 22, name: '用户KYC', route: '/business/pages/business_pages/user_kyc', file: 'business/pages/business_pages/user_kyc.vue', type: 'scene' },
    { id: 23, name: '积分兑换能量', route: '/business/pages/business_pages/activity_exchange', file: 'business/pages/business_pages/activity_exchange.vue', type: 'scene' },
    { id: 24, name: '积分账单', route: '/business/pages/business_pages/points_ledger', file: 'business/pages/business_pages/points_ledger.vue', type: 'business' },
    { id: 25, name: '认领店铺', route: '/bundle_user/pages/license/license', file: 'bundle_user/pages/license/license.vue', type: 'business' },
    { id: 26, name: '认领店铺2', route: '/bundle_user/pages/license/license?step=shop', file: 'bundle_user/pages/license/license.vue', type: 'business' },
    { id: 27, name: '认领店铺3', route: '/bundle_user/pages/license/license?step=details', file: 'bundle_user/pages/license/license.vue', type: 'business' },
    { id: 28, name: '认领店铺4', route: '/bundle_user/pages/license/license?step=realname', file: 'bundle_user/pages/license/license.vue', type: 'business' },
    { id: 29, name: '认领店铺5', route: '/bundle_user/pages/license/license?step=materials', file: 'bundle_user/pages/license/license.vue', type: 'business' },
    { id: 30, name: '购物车', route: '/pages/shop_cart/shop_cart', file: 'pages/shop_cart/shop_cart.vue', type: 'business', openType: 'switchTab' },
    { id: 31, name: '首页2', route: '/pages/index/index', file: 'pages/index/index.vue', type: 'business', openType: 'switchTab' }
]
