const localDesignAssets = {
    assets_category_tabbar_category_tab_cart_active_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_cart_active_fixed@2x.png',
    assets_category_tabbar_category_tab_cart_active_2x: '/static/lanhu/assets/category-tabbar/category_tab_cart_active@2x.png',
    assets_category_tabbar_category_tab_cart_normal_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_cart_normal_fixed@2x.png',
    assets_category_tabbar_category_tab_cart_normal_2x: '/static/lanhu/assets/category-tabbar/category_tab_cart_normal@2x.png',
    assets_category_tabbar_category_tab_category_active_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_category_active_fixed@2x.png',
    assets_category_tabbar_category_tab_category_active_2x: '/static/lanhu/assets/category-tabbar/category_tab_category_active@2x.png',
    assets_category_tabbar_category_tab_category_normal_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_category_normal_fixed@2x.png',
    assets_category_tabbar_category_tab_category_normal_2x: '/static/lanhu/assets/category-tabbar/category_tab_category_normal@2x.png',
    assets_category_tabbar_category_tab_home_active_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_home_active_fixed@2x.png',
    assets_category_tabbar_category_tab_home_active_2x: '/static/lanhu/assets/category-tabbar/category_tab_home_active@2x.png',
    assets_category_tabbar_category_tab_home_normal_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_home_normal_fixed@2x.png',
    assets_category_tabbar_category_tab_home_normal_2x: '/static/lanhu/assets/category-tabbar/category_tab_home_normal@2x.png',
    assets_category_tabbar_category_tab_street_active_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_street_active_fixed@2x.png',
    assets_category_tabbar_category_tab_street_active_2x: '/static/lanhu/assets/category-tabbar/category_tab_street_active@2x.png',
    assets_category_tabbar_category_tab_street_normal_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_street_normal_fixed@2x.png',
    assets_category_tabbar_category_tab_street_normal_2x: '/static/lanhu/assets/category-tabbar/category_tab_street_normal@2x.png',
    assets_category_tabbar_category_tab_user_active_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_user_active_fixed@2x.png',
    assets_category_tabbar_category_tab_user_active_2x: '/static/lanhu/assets/category-tabbar/category_tab_user_active@2x.png',
    assets_category_tabbar_category_tab_user_normal_fixed_2x: '/static/lanhu/assets/category-tabbar/category_tab_user_normal_fixed@2x.png',
    assets_category_tabbar_category_tab_user_normal_2x: '/static/lanhu/assets/category-tabbar/category_tab_user_normal@2x.png',
    assets_home_home2_balance_bill_2x: '/static/lanhu/assets/home/home2_balance_bill@2x.png',
    assets_home_home2_bg_2x: '/static/lanhu/assets/home/home2_bg@2x.png',
    assets_home_home2_buyer_illustration_2x: '/static/lanhu/assets/home/home2_buyer_illustration@2x.png',
    assets_home_home2_ecology_icon_2x: '/static/lanhu/assets/home/home2_ecology_icon@2x.png',
    assets_home_home2_hero_figure_2x: '/static/lanhu/assets/home/home2_hero_figure@2x.png',
    assets_home_home2_icon_more_2x: '/static/lanhu/assets/home/home2_icon_more@2x.png',
    assets_home_home2_notice_icon_2x: '/static/lanhu/assets/home/home2_notice_icon@2x.png',
    assets_home_home2_seller_illustration_2x: '/static/lanhu/assets/home/home2_seller_illustration@2x.png',
    assets_home_home2_shortcut_primary_2x: '/static/lanhu/assets/home/home2_shortcut_primary@2x.png',
    assets_home_home2_shortcut_secondary_2x: '/static/lanhu/assets/home/home2_shortcut_secondary@2x.png',
    assets_home_home2_shortcut_tertiary_2x: '/static/lanhu/assets/home/home2_shortcut_tertiary@2x.png',
    assets_my_my_about_2x: '/static/lanhu/assets/my/my_about@2x.png',
    assets_my_my_address_2x: '/static/lanhu/assets/my/my_address@2x.png',
    assets_my_my_alliance_code_2x: '/static/lanhu/assets/my/my_alliance_code@2x.png',
    assets_my_my_alliance_record_2x: '/static/lanhu/assets/my/my_alliance_record@2x.png',
    assets_my_my_arrow_circle_2x: '/static/lanhu/assets/my/my_arrow_circle@2x.png',
    assets_my_my_asset_panel_2x: '/static/lanhu/assets/my/my_asset_panel@2x.png',
    assets_my_my_avatar_default_2x: '/static/lanhu/assets/my/my_avatar_default@2x.png',
    assets_my_my_coupon_card_2x: '/static/lanhu/assets/my/my_coupon_card@2x.png',
    assets_my_my_ecology_2x: '/static/lanhu/assets/my/my_ecology@2x.png',
    assets_my_my_feedback_2x: '/static/lanhu/assets/my/my_feedback@2x.png',
    assets_my_my_gift_card_2x: '/static/lanhu/assets/my/my_gift_card@2x.png',
    assets_my_my_header_bg_2x: '/static/lanhu/assets/my/my_header_bg@2x.png',
    assets_my_my_kyc_2x: '/static/lanhu/assets/my/my_kyc@2x.png',
    assets_my_my_menu_capsule_2x: '/static/lanhu/assets/my/my_menu_capsule@2x.png',
    assets_my_my_merchant_arrow_2x: '/static/lanhu/assets/my/my_merchant_arrow@2x.png',
    assets_my_my_merchant_bg_2x: '/static/lanhu/assets/my/my_merchant_bg@2x.png',
    assets_my_my_offline_pay_2x: '/static/lanhu/assets/my/my_offline_pay@2x.png',
    assets_my_my_order_after_sale_2x: '/static/lanhu/assets/my/my_order_after_sale@2x.png',
    assets_my_my_order_pay_2x: '/static/lanhu/assets/my/my_order_pay@2x.png',
    assets_my_my_order_points_2x: '/static/lanhu/assets/my/my_order_points@2x.png',
    assets_my_my_order_receive_2x: '/static/lanhu/assets/my/my_order_receive@2x.png',
    assets_my_my_order_ship_2x: '/static/lanhu/assets/my/my_order_ship@2x.png',
    assets_my_my_page_bg_2x: '/static/lanhu/assets/my/my_page_bg@2x.png',
    assets_my_my_payment_record_2x: '/static/lanhu/assets/my/my_payment_record@2x.png',
    assets_my_my_points_card_2x: '/static/lanhu/assets/my/my_points_card@2x.png',
    assets_my_my_service_2x: '/static/lanhu/assets/my/my_service@2x.png',
    assets_my_my_setting_2x: '/static/lanhu/assets/my/my_setting@2x.png',
    assets_my_my_status_bar_2x: '/static/lanhu/assets/my/my_status_bar@2x.png',
    assets_my_my_strategy_banner_2x: '/static/lanhu/assets/my/my_strategy_banner@2x.png',
    assets_my_my_tab_user_2x: '/static/lanhu/assets/my/my_tab_user@2x.png',
    assets_my_my_value_alliance_2x: '/static/lanhu/assets/my/my_value_alliance@2x.png',
    assets_my_my_value_offline_2x: '/static/lanhu/assets/my/my_value_offline@2x.png',
    assets_my_my_value_online_2x: '/static/lanhu/assets/my/my_value_online@2x.png',
    assets_my_my_value_setting_2x: '/static/lanhu/assets/my/my_value_setting@2x.png',
    designs_01_feedback: '/static/lanhu/designs/01-feedback.png',
    designs_02_notice_detail: '/static/lanhu/designs/02-notice-detail.png',
    designs_03_store_detail: '/static/lanhu/designs/03-store-detail.png',
    designs_04_fiat_balance_2: '/static/lanhu/designs/04-fiat-balance-2.png',
    designs_05_street: '/static/lanhu/designs/05-street.png',
    designs_06_pending_payment: '/static/lanhu/designs/06-pending-payment.png',
    designs_07_store_qr: '/static/lanhu/designs/07-store-qr.png',
    designs_08_goods_qr: '/static/lanhu/designs/08-goods-qr.png',
    designs_09_store_group: '/static/lanhu/designs/09-store-group.png',
    designs_10_store_album: '/static/lanhu/designs/10-store-album.png',
    designs_11_fiat_balance: '/static/lanhu/designs/11-fiat-balance.png',
    designs_12_fiat_balance_3: '/static/lanhu/designs/12-fiat-balance-3.png',
    designs_13_payment_filter: '/static/lanhu/designs/13-payment-filter.png',
    designs_14_payment_record: '/static/lanhu/designs/14-payment-record.png',
    designs_15_cart: '/static/lanhu/designs/15-cart.png',
    designs_16_about_us: '/static/lanhu/designs/16-about-us.png',
    designs_17_activity_exchange: '/static/lanhu/designs/17-activity-exchange.png',
    designs_18_activity_center: '/static/lanhu/designs/18-activity-center.png',
    designs_19_card: '/static/lanhu/designs/19-card.png',
    designs_20_face_pay: '/static/lanhu/designs/20-face-pay.png',
    designs_21_recent_visits: '/static/lanhu/designs/21-recent-visits.png',
    designs_22_merchant_license: '/static/lanhu/designs/22-merchant-license.png',
    designs_23_street_goods: '/static/lanhu/designs/23-street-goods.png',
    designs_24_goods_detail: '/static/lanhu/designs/24-goods-detail.png',
    designs_25_eco_app: '/static/lanhu/designs/25-eco-app.png',
    designs_26_auto_points: '/static/lanhu/designs/26-auto-points.png',
    designs_27_search_list: '/static/lanhu/designs/27-search-list.png',
    designs_28_address_empty: '/static/lanhu/designs/28-address-empty.png',
    designs_29_address_edit: '/static/lanhu/designs/29-address-edit.png',
    designs_30_my_service: '/static/lanhu/designs/30-my-service.png',
    designs_31_my: '/static/lanhu/designs/31-my.png',
    designs_32_my_order: '/static/lanhu/designs/32-my-order.png',
    designs_33_notice: '/static/lanhu/designs/33-notice.png',
    designs_34_kyc: '/static/lanhu/designs/34-kyc.png',
    designs_35_category: '/static/lanhu/designs/35-category.png',
    designs_36_home_2: '/static/lanhu/designs/36-home-2.png'
}

const cloudDesignAssets = {
    assets_home_home2_balance_bill_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9566a7c565dd427b822bc943e931f327/home2_balance_bill_2x.png',
    assets_home_home2_bg_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c6e3f8ccd2fa479d9002153f9923d380/home2_bg_2x.png',
    assets_home_home2_buyer_illustration_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9d4e1073bfdd48fdae8b730d95f2898a/home2_buyer_illustration_2x.png',
    assets_home_home2_ecology_icon_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/e67a23615f1b4008b80fea223293cc90/home2_ecology_icon_2x.png',
    assets_home_home2_hero_figure_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c254677529a94ec7b76783a0b6b4ccd4/home2_hero_figure_2x.png',
    assets_home_home2_icon_more_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/2aeae5788ad74bea922b891d6553f28e/home2_icon_more_2x.png',
    assets_home_home2_notice_icon_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7cc4a5339aa544c1af514b9fbd953656/home2_notice_icon_2x.png',
    assets_home_home2_seller_illustration_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/6876bd3046304b20aa6d4c50491b76fa/home2_seller_illustration_2x.png',
    assets_home_home2_shortcut_primary_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/74a21f0693fb4ff6b96d61b4db99248c/home2_shortcut_primary_2x.png',
    assets_home_home2_shortcut_secondary_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/ff036a98304847049b09d8053548e16c/home2_shortcut_secondary_2x.png',
    assets_home_home2_shortcut_tertiary_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/912370819fc24848a944b4a7ead65031/home2_shortcut_tertiary_2x.png',
    assets_my_my_about_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/2e0089d47211404da15320bff4c633a4/my_about_2x.png',
    assets_my_my_address_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/354bfc7368024a808135f162c184c673/my_address_2x.png',
    assets_my_my_alliance_code_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/f5b3991ea4db4914b22d527cff7e0e00/my_alliance_code_2x.png',
    assets_my_my_alliance_record_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/25ff993a0bb0433bb83033c1dc06e9bb/my_alliance_record_2x.png',
    assets_my_my_arrow_circle_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/35491c35d51c435e8d5fd466338eaae8/my_arrow_circle_2x.png',
    assets_my_my_asset_panel_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/6a914e27478648d59997bd8d384e4dcd/my_asset_panel_2x.png',
    assets_my_my_avatar_default_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/e5a9916123194ac9aaf2d531412a8f31/my_avatar_default_2x.png',
    assets_my_my_coupon_card_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9790a38bb3234582898fb38a8cd48a0d/my_coupon_card_2x.png',
    assets_my_my_ecology_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/3367bad684324dbb8f77409050f749ab/my_ecology_2x.png',
    assets_my_my_feedback_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/fae46d994ce744c69b4fb64ab9dc0527/my_feedback_2x.png',
    assets_my_my_gift_card_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/5126936a0cad489685b1f184e28ccc44/my_gift_card_2x.png',
    assets_my_my_header_bg_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/64ae7d0c5ebf43b8ab46826c1cc27fbb/my_header_bg_2x.png',
    assets_my_my_kyc_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/8091ac6023434abd8b9196ac8be293cf/my_kyc_2x.png',
    assets_my_my_menu_capsule_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/1f52d8a5c355487eb578b084e7c863be/my_menu_capsule_2x.png',
    assets_my_my_merchant_arrow_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/ada2b80ea4114d7bb0fd1905626e2855/my_merchant_arrow_2x.png',
    assets_my_my_merchant_bg_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/fabb9e53537846a68e83d0cf5fad1925/my_merchant_bg_2x.png',
    assets_my_my_offline_pay_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7574cdbd9f2c427fbaff8048a2b8cbcb/my_offline_pay_2x.png',
    assets_my_my_order_after_sale_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/73cd412054fa41bfab5121e32704a7e0/my_order_after_sale_2x.png',
    assets_my_my_order_pay_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/0affa24c7d4d4aa58375757cd9cc9847/my_order_pay_2x.png',
    assets_my_my_order_points_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c0edd008af3a4bfdb7fd8b89154c72ae/my_order_points_2x.png',
    assets_my_my_order_receive_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/0183fa17062844ca8229ff5c08cf8d6b/my_order_receive_2x.png',
    assets_my_my_order_ship_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/2b359c50b2304daa9e22829e05066f74/my_order_ship_2x.png',
    assets_my_my_page_bg_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/a31e47dab4d240f4ba16a4b08ec4dcb1/my_page_bg_2x.png',
    assets_my_my_payment_record_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/a6d13179fa134a6eb8f93ea85565fd12/my_payment_record_2x.png',
    assets_my_my_points_card_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/3dc1f754181f4c619c3ab132840c48f4/my_points_card_2x.png',
    assets_my_my_service_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/877c645d9dcc4bea89cf747d69431729/my_service_2x.png',
    assets_my_my_setting_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/a960b001947a42fc897dd0238d549f47/my_setting_2x.png',
    assets_my_my_status_bar_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/beeeab68d8ef47ed82d35cc65ac46c68/my_status_bar_2x.png',
    assets_my_my_strategy_banner_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/8db70392bf4e4d0c9a750a6c10843338/my_strategy_banner_2x.png',
    assets_my_my_tab_user_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/95a07e3fa8bf4b23b61901a7b90d88fc/my_tab_user_2x.png',
    assets_my_my_value_alliance_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/e8f3fe6d8ad44ada866942f16f4f92ac/my_value_alliance_2x.png',
    assets_my_my_value_offline_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/42c1b6138c08467fb1ccfd4cbd34e47f/my_value_offline_2x.png',
    assets_my_my_value_online_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/3395e45b49d2484bae4d41bb5a195a3f/my_value_online_2x.png',
    assets_my_my_value_setting_2x: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/71b1979aa7c846709158770fcda08edb/my_value_setting_2x.png',
    designs_01_feedback: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/74ed5e50858642519ce45b612c7692fd/01-feedback.png',
    designs_02_notice_detail: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/04ea7f5c61c241df92648bc27200569b/02-notice-detail.png',
    designs_03_store_detail: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c00dcedf3cbe4c1dacc4b56e0c434a4b/03-store-detail.png',
    designs_04_fiat_balance_2: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/5ab7c61871574fe088a572d5d4c7b38e/04-fiat-balance-2.png',
    designs_05_street: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/545d582dc0784553993317a2849f5331/05-street.png',
    designs_06_pending_payment: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/40f933564afa49d49904696167aebc77/06-pending-payment.png',
    designs_07_store_qr: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/3600107ddc084d288d935fb05a317318/07-store-qr.png',
    designs_08_goods_qr: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/596bcd3918dd48ac9b4a090322da6432/08-goods-qr.png',
    designs_09_store_group: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/b9d0f4bf877541f7a5d6cd2baa3364a5/09-store-group.png',
    designs_10_store_album: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/4e7d4be41f7c4e65990419a1b3bf5f7f/10-store-album.png',
    designs_11_fiat_balance: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/db9dc82646aa43c1bccc0ba3fa0f0cc2/11-fiat-balance.png',
    designs_12_fiat_balance_3: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c4246f65a09f42dbb44065676d082658/12-fiat-balance-3.png',
    designs_13_payment_filter: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/970e718a53c04f088c62eb51f504dd35/13-payment-filter.png',
    designs_14_payment_record: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/cc7e0829d2fd4d569752a7b4d0b5b362/14-payment-record.png',
    designs_15_cart: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/b3b296dec5874195982b51c72ac736cd/15-cart.png',
    designs_16_about_us: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/b18158343212419f89c8d50002e15a55/16-about-us.png',
    designs_17_activity_exchange: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/fb8e79ca9083478fa7b4e8254be38d8f/17-activity-exchange.png',
    designs_18_activity_center: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/356011837d934c9f98f67fcb18060417/18-activity-center.png',
    designs_19_card: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/e2ca286ea53c474db27f8f6a82377c3b/19-card.png',
    designs_20_face_pay: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/aa5e654d6fed45daa04c2bc91c47eeaa/20-face-pay.png',
    designs_21_recent_visits: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c176c854e4734b838fe855658e743d48/21-recent-visits.png',
    designs_22_merchant_license: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7d58e17458874d54b2452a10998cd590/22-merchant-license.png',
    designs_23_street_goods: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/4b49613839bc46eb83a201c53ee70c46/23-street-goods.png',
    designs_24_goods_detail: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/28fd1b2e6bed4d9583ff01e364742450/24-goods-detail.png',
    designs_25_eco_app: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/794e959912c8494c96245c169e5eba87/25-eco-app.png',
    designs_26_auto_points: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/1207cc3c4f654403846f95f23e0b1e42/26-auto-points.png',
    designs_27_search_list: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/f721faf9084a4123a17d78110bd6116a/27-search-list.png',
    designs_28_address_empty: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/a8bd2247766c45f2aa14f81d8215b5e6/28-address-empty.png',
    designs_29_address_edit: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/121d5b22771c4335a413d3604bbfb7e4/29-address-edit.png',
    designs_30_my_service: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/4348a03a825e43cd94ad418ac0a204d6/30-my-service.png',
    designs_31_my: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/0669c5960b8b41dc83f2acf0b276c618/31-my.png',
    designs_32_my_order: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9aa426a22f28494b971b6d686c198885/32-my-order.png',
    designs_33_notice: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7523299a99d9487690426011b93879fe/33-notice.png',
    designs_34_kyc: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c4afdd149d2d4c7e8a52a32f363733fc/34-kyc.png',
    designs_35_category: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/5099ec2c4f7b41429059dfd0a5d6bcad/35-category.png',
    designs_36_home_2: 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/ad8f686ba63d457d94af4e02236a36df/36-home-2.png'
}

export const designAssetUrls = {
    '/static/lanhu/assets/home/home2_balance_bill@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9566a7c565dd427b822bc943e931f327/home2_balance_bill_2x.png',
    '/static/lanhu/assets/home/home2_bg@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c6e3f8ccd2fa479d9002153f9923d380/home2_bg_2x.png',
    '/static/lanhu/assets/home/home2_buyer_illustration@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9d4e1073bfdd48fdae8b730d95f2898a/home2_buyer_illustration_2x.png',
    '/static/lanhu/assets/home/home2_ecology_icon@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/e67a23615f1b4008b80fea223293cc90/home2_ecology_icon_2x.png',
    '/static/lanhu/assets/home/home2_hero_figure@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c254677529a94ec7b76783a0b6b4ccd4/home2_hero_figure_2x.png',
    '/static/lanhu/assets/home/home2_icon_more@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/2aeae5788ad74bea922b891d6553f28e/home2_icon_more_2x.png',
    '/static/lanhu/assets/home/home2_notice_icon@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7cc4a5339aa544c1af514b9fbd953656/home2_notice_icon_2x.png',
    '/static/lanhu/assets/home/home2_seller_illustration@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/6876bd3046304b20aa6d4c50491b76fa/home2_seller_illustration_2x.png',
    '/static/lanhu/assets/home/home2_shortcut_primary@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/74a21f0693fb4ff6b96d61b4db99248c/home2_shortcut_primary_2x.png',
    '/static/lanhu/assets/home/home2_shortcut_secondary@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/ff036a98304847049b09d8053548e16c/home2_shortcut_secondary_2x.png',
    '/static/lanhu/assets/home/home2_shortcut_tertiary@2x.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/912370819fc24848a944b4a7ead65031/home2_shortcut_tertiary_2x.png',
    '/static/lanhu/assets/my/my_about@2x.png': '/static/lanhu/assets/my/my_about@2x.png',
    '/static/lanhu/assets/my/my_address@2x.png': '/static/lanhu/assets/my/my_address@2x.png',
    '/static/lanhu/assets/my/my_alliance_code@2x.png': '/static/lanhu/assets/my/my_alliance_code@2x.png',
    '/static/lanhu/assets/my/my_alliance_record@2x.png': '/static/lanhu/assets/my/my_alliance_record@2x.png',
    '/static/lanhu/assets/my/my_arrow_circle@2x.png': '/static/lanhu/assets/my/my_arrow_circle@2x.png',
    '/static/lanhu/assets/my/my_asset_panel@2x.png': '/static/lanhu/assets/my/my_asset_panel@2x.png',
    '/static/lanhu/assets/my/my_avatar_default@2x.png': '/static/lanhu/assets/my/my_avatar_default@2x.png',
    '/static/lanhu/assets/my/my_coupon_card@2x.png': '/static/lanhu/assets/my/my_coupon_card@2x.png',
    '/static/lanhu/assets/my/my_ecology@2x.png': '/static/lanhu/assets/my/my_ecology@2x.png',
    '/static/lanhu/assets/my/my_feedback@2x.png': '/static/lanhu/assets/my/my_feedback@2x.png',
    '/static/lanhu/assets/my/my_gift_card@2x.png': '/static/lanhu/assets/my/my_gift_card@2x.png',
    '/static/lanhu/assets/my/my_header_bg@2x.png': '/static/lanhu/assets/my/my_header_bg@2x.png',
    '/static/lanhu/assets/my/my_kyc@2x.png': '/static/lanhu/assets/my/my_kyc@2x.png',
    '/static/lanhu/assets/my/my_menu_capsule@2x.png': '/static/lanhu/assets/my/my_menu_capsule@2x.png',
    '/static/lanhu/assets/my/my_merchant_arrow@2x.png': '/static/lanhu/assets/my/my_merchant_arrow@2x.png',
    '/static/lanhu/assets/my/my_merchant_bg@2x.png': '/static/lanhu/assets/my/my_merchant_bg@2x.png',
    '/static/lanhu/assets/my/my_offline_pay@2x.png': '/static/lanhu/assets/my/my_offline_pay@2x.png',
    '/static/lanhu/assets/my/my_order_after_sale@2x.png': '/static/lanhu/assets/my/my_order_after_sale@2x.png',
    '/static/lanhu/assets/my/my_order_pay@2x.png': '/static/lanhu/assets/my/my_order_pay@2x.png',
    '/static/lanhu/assets/my/my_order_points@2x.png': '/static/lanhu/assets/my/my_order_points@2x.png',
    '/static/lanhu/assets/my/my_order_receive@2x.png': '/static/lanhu/assets/my/my_order_receive@2x.png',
    '/static/lanhu/assets/my/my_order_ship@2x.png': '/static/lanhu/assets/my/my_order_ship@2x.png',
    '/static/lanhu/assets/my/my_page_bg@2x.png': '/static/lanhu/assets/my/my_page_bg@2x.png',
    '/static/lanhu/assets/my/my_payment_record@2x.png': '/static/lanhu/assets/my/my_payment_record@2x.png',
    '/static/lanhu/assets/my/my_points_card@2x.png': '/static/lanhu/assets/my/my_points_card@2x.png',
    '/static/lanhu/assets/my/my_service@2x.png': '/static/lanhu/assets/my/my_service@2x.png',
    '/static/lanhu/assets/my/my_setting@2x.png': '/static/lanhu/assets/my/my_setting@2x.png',
    '/static/lanhu/assets/my/my_status_bar@2x.png': '/static/lanhu/assets/my/my_status_bar@2x.png',
    '/static/lanhu/assets/my/my_strategy_banner@2x.png': '/static/lanhu/assets/my/my_strategy_banner@2x.png',
    '/static/lanhu/assets/my/my_tab_user@2x.png': '/static/lanhu/assets/my/my_tab_user@2x.png',
    '/static/lanhu/assets/my/my_value_alliance@2x.png': '/static/lanhu/assets/my/my_value_alliance@2x.png',
    '/static/lanhu/assets/my/my_value_offline@2x.png': '/static/lanhu/assets/my/my_value_offline@2x.png',
    '/static/lanhu/assets/my/my_value_online@2x.png': '/static/lanhu/assets/my/my_value_online@2x.png',
    '/static/lanhu/assets/my/my_value_setting@2x.png': '/static/lanhu/assets/my/my_value_setting@2x.png',
    '/static/lanhu/designs/01-feedback.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/74ed5e50858642519ce45b612c7692fd/01-feedback.png',
    '/static/lanhu/designs/02-notice-detail.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/04ea7f5c61c241df92648bc27200569b/02-notice-detail.png',
    '/static/lanhu/designs/03-store-detail.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c00dcedf3cbe4c1dacc4b56e0c434a4b/03-store-detail.png',
    '/static/lanhu/designs/04-fiat-balance-2.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/5ab7c61871574fe088a572d5d4c7b38e/04-fiat-balance-2.png',
    '/static/lanhu/designs/05-street.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/545d582dc0784553993317a2849f5331/05-street.png',
    '/static/lanhu/designs/06-pending-payment.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/40f933564afa49d49904696167aebc77/06-pending-payment.png',
    '/static/lanhu/designs/07-store-qr.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/3600107ddc084d288d935fb05a317318/07-store-qr.png',
    '/static/lanhu/designs/08-goods-qr.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/596bcd3918dd48ac9b4a090322da6432/08-goods-qr.png',
    '/static/lanhu/designs/09-store-group.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/b9d0f4bf877541f7a5d6cd2baa3364a5/09-store-group.png',
    '/static/lanhu/designs/10-store-album.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/4e7d4be41f7c4e65990419a1b3bf5f7f/10-store-album.png',
    '/static/lanhu/designs/11-fiat-balance.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/db9dc82646aa43c1bccc0ba3fa0f0cc2/11-fiat-balance.png',
    '/static/lanhu/designs/12-fiat-balance-3.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c4246f65a09f42dbb44065676d082658/12-fiat-balance-3.png',
    '/static/lanhu/designs/13-payment-filter.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/970e718a53c04f088c62eb51f504dd35/13-payment-filter.png',
    '/static/lanhu/designs/14-payment-record.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/cc7e0829d2fd4d569752a7b4d0b5b362/14-payment-record.png',
    '/static/lanhu/designs/15-cart.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/b3b296dec5874195982b51c72ac736cd/15-cart.png',
    '/static/lanhu/designs/16-about-us.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/b18158343212419f89c8d50002e15a55/16-about-us.png',
    '/static/lanhu/designs/17-activity-exchange.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/fb8e79ca9083478fa7b4e8254be38d8f/17-activity-exchange.png',
    '/static/lanhu/designs/18-activity-center.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/356011837d934c9f98f67fcb18060417/18-activity-center.png',
    '/static/lanhu/designs/19-card.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/e2ca286ea53c474db27f8f6a82377c3b/19-card.png',
    '/static/lanhu/designs/20-face-pay.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/aa5e654d6fed45daa04c2bc91c47eeaa/20-face-pay.png',
    '/static/lanhu/designs/21-recent-visits.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c176c854e4734b838fe855658e743d48/21-recent-visits.png',
    '/static/lanhu/designs/22-merchant-license.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7d58e17458874d54b2452a10998cd590/22-merchant-license.png',
    '/static/lanhu/designs/23-street-goods.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/4b49613839bc46eb83a201c53ee70c46/23-street-goods.png',
    '/static/lanhu/designs/24-goods-detail.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/28fd1b2e6bed4d9583ff01e364742450/24-goods-detail.png',
    '/static/lanhu/designs/25-eco-app.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/794e959912c8494c96245c169e5eba87/25-eco-app.png',
    '/static/lanhu/designs/26-auto-points.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/1207cc3c4f654403846f95f23e0b1e42/26-auto-points.png',
    '/static/lanhu/designs/27-search-list.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/f721faf9084a4123a17d78110bd6116a/27-search-list.png',
    '/static/lanhu/designs/28-address-empty.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/a8bd2247766c45f2aa14f81d8215b5e6/28-address-empty.png',
    '/static/lanhu/designs/29-address-edit.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/121d5b22771c4335a413d3604bbfb7e4/29-address-edit.png',
    '/static/lanhu/designs/30-my-service.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/4348a03a825e43cd94ad418ac0a204d6/30-my-service.png',
    '/static/lanhu/designs/31-my.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/0669c5960b8b41dc83f2acf0b276c618/31-my.png',
    '/static/lanhu/designs/32-my-order.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/9aa426a22f28494b971b6d686c198885/32-my-order.png',
    '/static/lanhu/designs/33-notice.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/7523299a99d9487690426011b93879fe/33-notice.png',
    '/static/lanhu/designs/34-kyc.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/c4afdd149d2d4c7e8a52a32f363733fc/34-kyc.png',
    '/static/lanhu/designs/35-category.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/5099ec2c4f7b41429059dfd0a5d6bcad/35-category.png',
    '/static/lanhu/designs/36-home-2.png': 'https://cy8bhf.mynatapp.cc/api/miniapp/files/miniapp/ad8f686ba63d457d94af4e02236a36df/36-home-2.png'
}

export function getDesignAsset(localPath) {
    if (localPath && localPath.indexOf('/static/lanhu/assets/category-tabbar/') === 0) {
        return localPath
    }
    return designAssetUrls[localPath] || localPath
}

export const designAssets = {
    ...localDesignAssets,
    ...cloudDesignAssets,
    myPageBg: getDesignAsset('/static/lanhu/assets/my/my_page_bg@2x.png'),
    myHeaderBg: getDesignAsset('/static/lanhu/assets/my/my_header_bg@2x.png'),
    myStatusBar: getDesignAsset('/static/lanhu/assets/my/my_status_bar@2x.png'),
    myMenuCapsule: getDesignAsset('/static/lanhu/assets/my/my_menu_capsule@2x.png'),
    myAvatarDefault: getDesignAsset('/static/lanhu/assets/my/my_avatar_default@2x.png'),
    mySetting: getDesignAsset('/static/lanhu/assets/my/my_setting@2x.png'),
    myMerchantBg: getDesignAsset('/static/lanhu/assets/my/my_merchant_bg@2x.png'),
    myMerchantArrow: getDesignAsset('/static/lanhu/assets/my/my_merchant_arrow@2x.png'),
    myAssetPanel: getDesignAsset('/static/lanhu/assets/my/my_asset_panel@2x.png'),
    myGiftCard: getDesignAsset('/static/lanhu/assets/my/my_gift_card@2x.png'),
    myPointsCard: getDesignAsset('/static/lanhu/assets/my/my_points_card@2x.png'),
    myCouponCard: getDesignAsset('/static/lanhu/assets/my/my_coupon_card@2x.png'),
    myStrategyBanner: getDesignAsset('/static/lanhu/assets/my/my_strategy_banner@2x.png'),
    myTabUser: getDesignAsset('/static/lanhu/assets/my/my_tab_user@2x.png'),
    myArrowCircle: getDesignAsset('/static/lanhu/assets/my/my_arrow_circle@2x.png'),
    myOrderPay: getDesignAsset('/static/lanhu/assets/my/my_order_pay@2x.png'),
    myOrderShip: getDesignAsset('/static/lanhu/assets/my/my_order_ship@2x.png'),
    myOrderReceive: getDesignAsset('/static/lanhu/assets/my/my_order_receive@2x.png'),
    myOrderPoints: getDesignAsset('/static/lanhu/assets/my/my_order_points@2x.png'),
    myOrderAfterSale: getDesignAsset('/static/lanhu/assets/my/my_order_after_sale@2x.png'),
    myOfflinePay: getDesignAsset('/static/lanhu/assets/my/my_offline_pay@2x.png'),
    myPaymentRecord: getDesignAsset('/static/lanhu/assets/my/my_payment_record@2x.png'),
    myAllianceCode: getDesignAsset('/static/lanhu/assets/my/my_alliance_code@2x.png'),
    myAllianceRecord: getDesignAsset('/static/lanhu/assets/my/my_alliance_record@2x.png'),
    myValueOnline: getDesignAsset('/static/lanhu/assets/my/my_value_online@2x.png'),
    myValueOffline: getDesignAsset('/static/lanhu/assets/my/my_value_offline@2x.png'),
    myValueAlliance: getDesignAsset('/static/lanhu/assets/my/my_value_alliance@2x.png'),
    myValueSetting: getDesignAsset('/static/lanhu/assets/my/my_value_setting@2x.png'),
    myKyc: getDesignAsset('/static/lanhu/assets/my/my_kyc@2x.png'),
    myAddress: getDesignAsset('/static/lanhu/assets/my/my_address@2x.png'),
    myFeedback: getDesignAsset('/static/lanhu/assets/my/my_feedback@2x.png'),
    myEcology: getDesignAsset('/static/lanhu/assets/my/my_ecology@2x.png'),
    myAbout: getDesignAsset('/static/lanhu/assets/my/my_about@2x.png'),
    myService: getDesignAsset('/static/lanhu/assets/my/my_service@2x.png'),
    homeBalanceBill: getDesignAsset('/static/lanhu/assets/home/home2_balance_bill@2x.png'),
    homeBuyerIllustration: getDesignAsset('/static/lanhu/assets/home/home2_buyer_illustration@2x.png'),
    homeEcologyIcon: getDesignAsset('/static/lanhu/assets/home/home2_ecology_icon@2x.png'),
    homeHeroBg: getDesignAsset('/static/lanhu/assets/home/home2_bg@2x.png'),
    homeHeroFigure: getDesignAsset('/static/lanhu/assets/home/home2_hero_figure@2x.png'),
    homeNoticeIcon: getDesignAsset('/static/lanhu/assets/home/home2_notice_icon@2x.png'),
    homeSellerIllustration: getDesignAsset('/static/lanhu/assets/home/home2_seller_illustration@2x.png'),
    homeShortcutPrimary: getDesignAsset('/static/lanhu/assets/home/home2_shortcut_primary@2x.png'),
    homeShortcutSecondary: getDesignAsset('/static/lanhu/assets/home/home2_shortcut_secondary@2x.png'),
    homeShortcutTertiary: getDesignAsset('/static/lanhu/assets/home/home2_shortcut_tertiary@2x.png'),
    homeMoreIcon: getDesignAsset('/static/lanhu/assets/home/home2_icon_more@2x.png'),
    categoryTabHomeNormal: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_home_normal_fixed@2x.png'),
    categoryTabHomeActive: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_home_active_fixed@2x.png'),
    categoryTabCategoryNormal: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_category_normal_fixed@2x.png'),
    categoryTabCategoryActive: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_category_active_fixed@2x.png'),
    categoryTabStreetNormal: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_street_normal_fixed@2x.png'),
    categoryTabStreetActive: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_street_active_fixed@2x.png'),
    categoryTabCartNormal: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_cart_normal_fixed@2x.png'),
    categoryTabCartActive: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_cart_active_fixed@2x.png'),
    categoryTabUserNormal: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_user_normal_fixed@2x.png'),
    categoryTabUserActive: getDesignAsset('/static/lanhu/assets/category-tabbar/category_tab_user_active_fixed@2x.png')
}

export const designAssetList = {
    homeShortcuts: [
        designAssets.homeShortcutPrimary,
        designAssets.homeShortcutSecondary,
        designAssets.homeShortcutTertiary
    ],
    categoryFallbacks: [
        getDesignAsset('/static/lanhu/designs/35-category.png'),
        getDesignAsset('/static/lanhu/designs/17-activity-exchange.png'),
        getDesignAsset('/static/lanhu/designs/23-street-goods.png')
    ],
    sceneAlbum: [
        getDesignAsset('/static/lanhu/designs/10-store-album.png'),
        getDesignAsset('/static/lanhu/designs/21-recent-visits.png'),
        getDesignAsset('/static/lanhu/designs/23-street-goods.png'),
        getDesignAsset('/static/lanhu/designs/27-search-list.png')
    ]
}
